name = "void"
license = "Unlicense"
description = "A simple & dark theme for blogs"
homepage = "https://tek256.com/"
tags = ["blog","simple","minimal","clean","dark"]
features = ["blog", "Clean", "Dark"]
min_version = "0.41.0"

[author]
  name = "tek256"
  homepage = "https://tek256.com/"

